name: Rebuild image when parent-image changes

# Regularly check at 4 AM
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository. You don't need this for the check to work, but putting it here saves you an "if: ..."
      - name: Checkout
        uses: actions/checkout@v2

      # Now check if our parent image changed. The result will be available at `steps.[id of this step].outputs.out-of-date`
      - name: Check if we have to even do all this
        id: check
        uses: twiddler/is-my-docker-parent-image-out-of-date@v1
        with:
          parent-image: matrixdotorg/synapse:latest
          my-image: ghcr.io/rexjohannes/synapse:latest

      # We only want to build and push if our parent image changed.
      - name: Build and push
        uses: rexjohannes/matrix-synapse-s3-docker/.github/workflows/docker-publish.yml@main
        # Add this line to all the steps you want to skip
        if: steps.check.outputs.out-of-date == 'true'
